// <auto-generated />
using System;
using Marketing_Sc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Marketing_Sc.Migrations
{
    [DbContext(typeof(Marketing_ScContext))]
    partial class Marketing_ScContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Marketing_Sc.Entidades.Campania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CajaChica")
                        .HasColumnType("numeric");

                    b.Property<int>("CantidadProductoSolicitado")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadVendedores")
                        .HasColumnType("integer");

                    b.Property<string>("CombosPromocionales")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GastoAntes")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GastoDespues")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GastoDurante")
                        .HasColumnType("numeric");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductoSolicitado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ViaticosAsignados")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Campania");
                });
#pragma warning restore 612, 618
        }
    }
}
